project:
  type: website
  output-dir: docs

website:
  title: "Keller Lab"  
  description: "The lab website of Stephen R. Keller"
  image: img/LogoBlack_square.png
  favicon: img/LogoBlack_square.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/small_logo3.png
    
    # your sub-pages
    left:
      - text: "Research"
        href: research/research.qmd
      - text: "People"
        href: people/people.qmd
      - text: "Publications"
        href: publications/publications.qmd
      - text: "Photos"
        href: photos/photos.qmd
      
    
    # your social media handles
    right:
      - icon: twitter-x
        href: https://twitter.com/KellerLabUVM
      - icon: google
        href: https://scholar.google.com/citations?user=cYPEa5gAAAAJ&hl=en
      - icon: github
        href: https://github.com/stephenrkeller
      - icon: envelope
        aria-label: email
        href: "mailto:srkeller@uvm.edu"
        
  # person-workspace
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    center: |
      <span class="faux-block">
      Â© Copyright <span id="year"></span>, Keller lab | Ecological Genomics
      </span>
      <script>
        document.getElementById("year").textContent = new Date().getFullYear();
      </script>
 
format:
  html:
    fontsize: 1.1em
    theme: 
      # - litera
      - style2.scss
    toc: true
    toc-depth: 4
    toc-title: ""
    footnotes-hover: true
    highlight-style: tango